Traceback (most recent call last):
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/uncoder/sm6-books/computer-sim-labs/.venv/lib/python3.10/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# –ò–Ω–∏—Ü–∏–∞–ª–∏–∑–∞—Ü–∏—è –∏—Å—Ö–æ–¥–Ω—ã—Ö –¥–∞–Ω–Ω—ã—Ö
params = LBEParams(...)
# –ò–Ω–∏—Ü–∏–∞–ª–∏–∑–∞—Ü–∏—è —Ä–µ—à–∞—Ç–µ–ª—è
solver = LBESolver(params)
# –†–µ—à–µ–Ω–∏–µ –∑–∞–¥–∞—á–∏ + –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è
solver.solve(...)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 6[0m
[1;32m      4[0m solver [38;5;241m=[39m LBESolver(params)
[1;32m      5[0m [38;5;66;03m# –†–µ—à–µ–Ω–∏–µ –∑–∞–¥–∞—á–∏ + –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è[39;00m
[0;32m----> 6[0m [43msolver[49m[38;5;241;43m.[39;49m[43msolve[49m[43m([49m[38;5;241;43m.[39;49m[38;5;241;43m.[39;49m[38;5;241;43m.[39;49m[43m)[49m

Cell [0;32mIn[3], line 30[0m, in [0;36mLBESolver.solve[0;34m(self, iters, n_pics)[0m
[1;32m     23[0m [38;5;250m[39m[38;5;124;03m"""–û—Å–Ω–æ–≤–Ω–æ–π –º–µ—Ç–æ–¥ —Ä–µ—à–∞—Ç–µ–ª—è.[39;00m
[1;32m     24[0m [38;5;124;03m[39;00m
[1;32m     25[0m [38;5;124;03m* `iters`: –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∏—Ç–µ—Ä–∞—Ü–∏–π —Ä–∞—Å—á—ë—Ç–∞.[39;00m
[1;32m     26[0m [38;5;124;03m* `n_pics`: –∫–æ–ª–∏—á–µ—Å—Ç–≤–æ –∫–∞—Ä—Ç–∏–Ω–æ–∫, –∫–æ—Ç–æ—Ä–æ–µ –Ω–µ–æ–±—Ö–æ–¥–∏–º–æ —Å–æ—Ö—Ä–∞–Ω–∏—Ç—å[39;00m
[1;32m     27[0m [38;5;124;03m  —á–µ—Ä–µ–∑ —Ä–∞–≤–Ω—ã–µ –ø—Ä–æ–º–µ–∂—É—Ç–∫–∏ –≤—Ä–µ–º–µ–Ω–∏.[39;00m
[1;32m     28[0m [38;5;124;03m"""[39;00m
[1;32m     29[0m [38;5;66;03m# TODO: –í–∞—à–∞ —Ä–µ–∞–ª–∏–∑–∞—Ü–∏—è —Å–æ–≥–ª–∞—Å–Ω–æ –º–µ—Ç–æ–¥–∏—á–µ—Å–∫–∏–º —É–∫–∞–∑–∞–Ω–∏—è–º (–ø—É–Ω–∫—Ç—ã 1-6)[39;00m
[0;32m---> 30[0m [38;5;28;01mfor[39;00m time [38;5;129;01min[39;00m [38;5;28;43mrange[39;49m[43m([49m[43miters[49m[43m)[49m:
[1;32m     31[0m     [38;5;66;03m# TODO: –ø—É–Ω–∫—Ç 7 –º–µ—Ç–æ–¥–∏—á–µ—Å–∫–∏—Ö —É–∫–∞–∑–∞–Ω–∏–π[39;00m
[1;32m     32[0m     [38;5;66;03m# –∏ –≤–∏–∑—É–∞–ª–∏–∑–∞—Ü–∏—è —á–µ—Ä–µ–∑ –∫–∞–∂–¥—ã–µ iters // n_pics[39;00m
[1;32m     33[0m     [38;5;28;01mpass[39;00m

[0;31mTypeError[0m: 'ellipsis' object cannot be interpreted as an integer

